### ISSUE TITLE
altjs.org is gone. It seems

### ISSUE THREAD

**Issue by smurfpandey** [survivejs/js_tricks_and_tips#28]
http://survivejs.com/a_misunderstood_language/altjs.html

here altjs.org is mentioned to have a list of languages, but it seems that domain has been bought by someone else. It's redirecting  to a Japanese site instead.

**Comment by bebraw** [comment]
Thanks! Fixed. I made it to point at https://github.com/jashkenas/coffeescript/wiki/list-of-languages-that-compile-to-js as that seems to be actively maintained.

**Comment by smurfpandey** [comment]
:+1:
